### ISSUE TITLE
AutoML Adapters Cannot Write Output

### ISSUE THREAD

**Issue by jnnks** [hochschule-darmstadt/MetaAutoML#79]
The adapters crash while trying to write their output logs. Log from autokeras:
```python
autokeras     | Traceback (most recent call last):
autokeras     |   File "AutoML.py", line 18, in <module>
autokeras     |     tabular_data_automl.execute_task()
autokeras     |   File "/app/AutoMLs/TabularDataAutoML.py", line 51, in execute_task
autokeras     |     self.__classification()
autokeras     |   File "/app/AutoMLs/TabularDataAutoML.py", line 64, in __classification
autokeras     |     self.__export_model(clf)
autokeras     |   File "/app/AutoMLs/TabularDataAutoML.py", line 45, in __export_model
autokeras     |     with open(os.path.join(get_config_property('output-path'), 'tmp', 'model_keras.p'), 'wb+') as file:
autokeras     | FileNotFoundError: [Errno 2] No such file or directory: 'app-data/output/tmp/model_keras.p'
```
`get_config_property('output-path')` will return `app-data/output` which does not have a subdir `tmp`.
This is likely a docker-compose issue. We are creating that directory in the Dockerifles, but overwrite it with during docker-compose up.

**Directory is created here:** https://github.com/hochschule-darmstadt/MetaAutoML/blob/fd9bcbabc2cbe5b7b192e175bc288d3bc6285afc/adapters/AutoKeras/Dockerfile#L15

**Parent directory is overwritten here:** https://github.com/hochschule-darmstadt/MetaAutoML/blob/fd9bcbabc2cbe5b7b192e175bc288d3bc6285afc/docker-compose.yml#L57

This affects *at least* autokeras and mljar, but the others should fail too.

**Comment by jnnks** [comment]
The error cannot be reproduced after rebuilding the containers. Will be closed until relevant again
